# vim: set noexpandtab tabstop=4 shiftwidth=4 softtabstop=4 filetype=zsh:

# Executes commands at the start of an interactive session.
[[ $_zsh_trace ]] && echo ">> zshrc"

# Source Prezto.
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

[[ -f $DOTFILES_PATH/shell_functions.sh ]] && source "$DOTFILES_PATH/shell_functions.sh"
[[ -f $HOME/.profile ]] && source $HOME/.profile

if command -v direnv >/dev/null 2>&1; then
	eval "$(direnv hook zsh)"
fi

# set the tmux pane title to the basename of the working directory as a default
set-pane-title

[[ $_zsh_trace ]] && echo "<< zshrc" || :
